name: anbd
description: "ANBD"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_svg: ^2.0.17
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.2.0+3
  change_app_package_name: ^1.5.0
  timeago: ^3.5.0

  # router
  go_router: ^14.8.0

  # 상태 관리
  provider: ^6.0.5

  # network
  dio: ^5.3.2

  # 위치 정보 가져오기
  geolocator: ^13.0.0

  # 저장소
  flutter_secure_storage: ^8.0.0
  flutter_config: ^2.0.2
  shared_preferences: ^2.2.2

  # 구글 로그인
  google_sign_in: ^6.2.1

  # 구글 map api
  google_maps_flutter: ^2.10.1

  # 구글 장소 검색 api
  google_places_flutter: ^2.1.0
  flutter_google_maps_webservices: ^1.1.1

  # 직렬화 Freezed
  freezed_annotation: ^2.0.3
  freezed: ^2.0.3

  # 모델 만들기
  json_annotation: ^4.9.0
  json_serializable: ^6.7.0

  #DI
  get_it: ^7.7.0

  # build runner
  build_runner: ^2.4.11

  # date picker
  syncfusion_flutter_datepicker: ^28.2.12

  #날 형식 변환
  intl: ^0.19.0
  permission_handler: ^11.3.1

  # 디바이스 이미지 불러오기
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/svg/
    - assets/svg/category/
    - assets/images/login/
    - assets/images/onboarding/
    - assets/images/

  fonts:
    - family: PretendardRegular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf

    - family: PretendardSemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.ttf

    - family: PretendardMedium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.ttf

    - family: PretendardExtraBold
      fonts:
        - asset: assets/fonts/Pretendard-ExtraBold.ttf

    - family: PretendardLight
      fonts:
        - asset: assets/fonts/Pretendard-Light.ttf

    - family: PretendardBold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf