name: anbd
description: "ANBD"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  intl: ^0.18.0
  provider: ^6.0.5
  flutter_svg: ^2.0.17
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.2.0+3
  go_router: ^14.8.0
  change_app_package_name: ^1.5.0

  # network
  dio: ^5.3.2

  # 위치 정보 가져오기
  geolocator: ^13.0.0

  #토큰 저장소
  flutter_secure_storage: ^8.0.0
  flutter_config: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/svg/category/
    - assets/images/login/
    - assets/images/onboarding/
    - assets/images/

  fonts:
    - family: PretendardRegular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf

    - family: PretendardSemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.ttf

    - family: PretendardMedium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.ttf

    - family: PretendardEtraBold
      fonts:
        - asset: assets/fonts/Pretendard-ExtraBold.ttf

    - family: PretendardLight
      fonts:
        - asset: assets/fonts/Pretendard-Light.ttf